### ISSUE TITLE
online editor not working anymore ?

### ISSUE THREAD

**Issue by simogeo** [SparkPost/heml#103]
https://heml.io/editor/

From developer console (F12) : 

```
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://heml-api.herokuapp.com/. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant. Code d’état : 404.

Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://heml-api.herokuapp.com/. Raison : échec de la requête CORS. Code d’état : (null).

Uncaught (in promise) Error: Network Error
    createError createError.js:16
    handleError xhr.js:87
```

**Comment by VILLAN3LL3** [comment]
Here the English version of the error messages:

> Access to XMLHttpRequest at 'https://heml-api.herokuapp.com/' from origin 'https://heml.io' has been blocked by CORS > policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on > the requested resource.
> heml-api.herokuapp.com/:1 
> Failed to load resource: net::ERR_FAILED
> createError.js:16 
>         
>        Uncaught (in promise) Error: Network Error
>     at createError (createError.js:16:1)
>     at XMLHttpRequest.handleError (xhr.js:87:1)

**Comment by ManuelFeller** [comment]
It seems that the API server was a victim of Herokus "shut down" of the free plan :(
https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq
