### ISSUE TITLE
Cannot find module './Button'

### ISSUE THREAD

**Issue by obfuscatedgeek** [SparkPost/heml#45]
I am getting this error since today

``` 
Error: Cannot find module './Button'
           at Function.Module._resolveFilename (module.js:536:15)
           at Function.Module._load (module.js:466:25)
           at Module.require (module.js:579:17)
           at require (internal/module.js:11:18)
           at Object.<anonymous> (/usr/src/app/node_modules/@heml/elements/build/index.js:68:15)
           at Module._compile (module.js:635:30)
           at Object.Module._extensions..js (module.js:646:10)
           at Module.load (module.js:554:32)
           at tryModuleLoad (module.js:497:12)
           at Function.Module._load (module.js:489:3)
           at Module.require (module.js:579:17)
           at require (internal/module.js:11:18)
           at Object.<anonymous> (/usr/src/app/node_modules/heml/build/index.js:126:17)
           at Module._compile (module.js:635:30)
           at Object.Module._extensions..js (module.js:646:10)
           at Module.load (module.js:554:32)
```

Was getting error on the previous version ^1.0.2-0.
Upgraded to the new version today and still the same error, any clues ?

Thanks

**Comment by avigoldman** [comment]
Hey @obfuscatedgeek 👋  Would you mind giving some of your environment information. Node version and OS would be a good start.

**Comment by obfuscatedgeek** [comment]
Hi @avigoldman thanks for quick response.

It fails on my docker environment running NodeJS 8.1.0

**Comment by avigoldman** [comment]
Hmmm ok...what OS?

**Comment by avigoldman** [comment]
Looks like the button file is named `button.js` but it is being included as `./Button`. Good chance that is the issue. Can you do an install from the [button-case-issue](https://github.com/SparkPost/heml/tree/button-case-issue) branch, and see if it works properly?

**Comment by obfuscatedgeek** [comment]
Cool. Will check in an hour and update you.

**Comment by obfuscatedgeek** [comment]
OK back but no progress.

I am trying to install from the branch but npm keeps failing saying `Missing package name` :(

**Comment by avigoldman** [comment]
Whoops, my bad! I didn't think it through. Here are the steps to install from the repo.

```
git clone https://github.com/SparkPost/heml
cd heml
npm install && npm run bootstrap && npm run build
```

Then you should be able to run the CLI like so (from that directory)
`./packages/heml/build/bin/heml.js build my-template.heml`

**Comment by obfuscatedgeek** [comment]
Sweet! that works. Able to run from CLI

**Comment by avigoldman** [comment]
Awesome! I'll merge that in and push out a patch

**Comment by avigoldman** [comment]
You should be good to install `1.1.3`! Let me know if you hit any other issues 😄

**Comment by obfuscatedgeek** [comment]
Awesome work mate! Works perfectly! Thank you very much
